server:
  host:
  port:
settings:
  loglevel:
  serviceHealthStatusRefreshRate:
  serviceHealthIssueKeepDays:
oneDrive:
  enabled: true
  scrambleNames: true
  scrambleSalt:
teams:
  enabled: true
adsync:
  enabled: true
exchange:
  enabled: true
securescore:
  enabled: true
license:
  enabled: true
servicehealth:
  enabled: true
intune:
  enabled: true
entraid:
  enabled: true
sharepoint:
  enabled: true
